name: Build
on: [push]
jobs:
  build:
    name: Build & Test

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.15.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set up Go v${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -race -cover -coverprofile="coverage.out" -covermode=atomic ./...

      - name: Codecov
        uses: codecov/codecov-action@v1
